// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytwjygdatwyyoxozqfat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0d2p5Z2RhdHd5eW94b3pxZmF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4NjQwNzIsImV4cCI6MjA1MjQ0MDA3Mn0.XBU2DqSJhINj5WWsieaKSbTc4NpnckhRPmzZDRf56oo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);